project:
  type: website
  output-dir: docs
  
website:
  title: "STOCKS WEB SITE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - href: docs/arima_model.ipynb
        text: Arima model
      - href: docs/arima_predictive_notebook.ipynb
        text: Arima Predictions
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/romanmmr/stocks_site
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Rodrigo Roman"

format:
  html:
    theme: sketchy
    toc: true

editor: source